// Generated by https://quicktype.io

export interface PostModel {
  username: string;
  post: string;
  totalLikes: number;
  created: string;
  _id: string;
  user: User;
  comments: any[];
  likes: any[];
  __v: number;
}

export interface User {
  _id: string;
  username: string;
  email: string;
  password: string;
  posts: Post[];
  __v: number;
}

export interface Post {
  createdAt: string;
  _id: ID;
  postId: PostID;
  post: string;
}

export enum ID {
  The5B801E4B89Eb6524Aff3F23E = '5b801e4b89eb6524aff3f23e',
  The5B80B4782Ab8821129Ede942 = '5b80b4782ab8821129ede942',
  The5B80Bef40Ab8721Ae08Da11D = '5b80bef40ab8721ae08da11d'
}

export enum PostID {
  The5B801E4B89Eb6524Aff3F23D = '5b801e4b89eb6524aff3f23d',
  The5B80B4782Ab8821129Ede941 = '5b80b4782ab8821129ede941',
  The5B80Bef40Ab8721Ae08Da11C = '5b80bef40ab8721ae08da11c'
}
